# Copyright (c) 2026
#
# Hochschule Offenburg, University of Applied Sciences
# Institute for reliable Embedded Systems
# and Communications Electronic (ivESK)
#
# This file is licensed as described in the "LICENSE" file
# included within the root folder of this work.

"""SPsec constants/enums, matching the C implementation headers."""

import os

# Message types (from common/include/messages.h)
SPSEC_MSGTYPE_CLIENT_HELLO = 1
SPSEC_MSGTYPE_SERVER_HELLO = 2
SPSEC_MSGTYPE_CLIENT_FINISHED = 3
SPSEC_MSGTYPE_SERVER_FINISHED = 4
SPSEC_MSGTYPE_CLIENT_READ_INITIATE = 5
SPSEC_MSGTYPE_SERVER_READ_INITIATE = 6
SPSEC_MSGTYPE_CLIENT_READ_SEGMENT = 7
SPSEC_MSGTYPE_SERVER_READ_SEGMENT = 8
SPSEC_MSGTYPE_CLIENT_WRITE_INITIATE = 9
SPSEC_MSGTYPE_SERVER_WRITE_INITIATE = 10
SPSEC_MSGTYPE_CLIENT_WRITE_SEGMENT = 11
SPSEC_MSGTYPE_SERVER_WRITE_SEGMENT = 12
SPSEC_MSGTYPE_CLIENT_TERMINATE = 13
SPSEC_MSGTYPE_SERVER_TERMINATE = 14
SPSEC_MSGTYPE_TIME_SYNC_REQUEST = 15
SPSEC_MSGTYPE_TIME_SYNC_RESPONSE = 16
SPSEC_MSGTYPE_SYNC_TIME_BROADCAST = 17
SPSEC_MSGTYPE_HEARTBEAT = 18
SPSEC_MSGTYPE_SECURITY_EVENT = 19
SPSEC_MSGTYPE_INTERNAL_EVENT = 20
SPSEC_MSGTYPE_APP_DATA = 21

# Control plane types (from common/include/messages.h)
SPSEC_CPMT_SESS_HELLO = 0
SPSEC_CPMT_SESS_FINISH = 1
SPSEC_CPMT_SESS_RDINIT = 2
SPSEC_CPMT_SESS_RDSEG = 3
SPSEC_CPMT_SESS_WRINIT = 4
SPSEC_CPMT_SESS_WRSEG = 5
SPSEC_CPMT_SESS_TERMINATE = 6
SPSEC_CPMT_RESERVED_7 = 7
SPSEC_CPMT_AUTH = 8
SPSEC_CPMT_SYNC = 9
SPSEC_CPMT_HB = 10
SPSEC_CPMT_RESERVED_11 = 11
SPSEC_CPMT_INTERN_EVT = 12

# SPsec Participant States (from common/include/spsec_registers.h)
SPSEC_STATE_NOT_SET = 0
SPSEC_STATE_WAITING = 1
SPSEC_STATE_SECURE = 2
SPSEC_STATE_WARNING = 3
SPSEC_STATE_CONFIGURATION = 4
SPSEC_STATE_SHUTDOWN = 5

# Register Address Definitions (from common/include/spsec_registers.h)
SPSEC_REG_PROVISIONING_KEY = 0x21
SPSEC_REG_INTEGRATOR_KEY = 0x22
SPSEC_REG_SEED_KEY = 0x23
SPSEC_REG_PROVISIONING_KEY_SALT = 0x31
SPSEC_REG_INTEGRATOR_KEY_SALT = 0x32
SPSEC_REG_SEED_KEY_SALT = 0x33
SPSEC_REG_PROVISIONING_KEY_ID = 0x41
SPSEC_REG_INTEGRATOR_KEY_ID = 0x42
SPSEC_REG_SEED_KEY_ID = 0x43
SPSEC_REG_STATUS = 0x50
SPSEC_REG_LAST_SECURITY_EVENT = 0x51
SPSEC_REG_CORE_VERSION_INFO = 0x58
SPSEC_REG_MAPPING_VERSION_INFO = 0x59
SPSEC_REG_PARTICIPANT_ID = 0x60
SPSEC_REG_SECURE_HEARTBEAT_TIMING = 0x61
SPSEC_REG_SECURE_HEARTBEAT_MONITOR = 0x62
SPSEC_REG_DEVICE_IDENTIFICATION = 0x81
SPSEC_REG_MCU_SERIAL_NUMBER = 0x82

# Manufacturer Reset & Sync Role Registers (SPsec302 / SPsec201)
SPSEC_REG_SYNC_ROLE_ACTIVATION = 0x63
SPSEC_REG_MANUFACTURER_RESET = 0x7F
# Manufacturer Reset value (0x1D04E5E1, register 0x7F) in little-endian format
SPSEC_MANUFACTURER_RESET_MAGIC = b"\xE1\xE5\x04\x1D"

# Key Selectors (from common/include/spsec_registers.h)
SPSEC_KEY_SELECTOR_ZERO_KEY = 1
SPSEC_KEY_SELECTOR_SESSION_KEY = 2
SPSEC_KEY_SELECTOR_EVEN_COMM_KEY = 3
SPSEC_KEY_SELECTOR_ODD_COMM_KEY = 4
SPSEC_KEY_SELECTOR_SEED_KEY = 13
SPSEC_KEY_SELECTOR_INTEGRATOR_KEY = 14
SPSEC_KEY_SELECTOR_PROVISIONING_KEY = 15

# SPsec CAN ID Address Bases
SPSEC_ADDRESS_HEARTBEAT_BASE = 0x12000000
SPSEC_ADDRESS_SESSION_BASE = 0x1E000000
SPSEC_ADDRESS_DISCOVERY_BASE = 0x1EFF0000

# Addressing flags
SPSEC_ADDRESS_DESTINATION_BIT = 0x80
SPSEC_CAN_ID_MASK = 0x1FFFFFFF
SPSEC_CAN_EFF_FLAG = 0x80000000

# Global constants
AUTH_TAG_SIZE = 8
RANDOM_SIZE = 16
KEY_LEN = 32
# Pre-shared salt length (default 8, overridable via SPSEC_SALT_LEN)
SALT_LEN = int(os.getenv("SPSEC_SALT_LEN", "8"))
REQUIRED_NONCE_LEN = 16

#: Key material slots in storage order (0: Zero, 1: Prov, 2: Int, 3: Seed)
SPSEC_KEY_SELECTORS = [
    SPSEC_KEY_SELECTOR_ZERO_KEY,
    SPSEC_KEY_SELECTOR_PROVISIONING_KEY,
    SPSEC_KEY_SELECTOR_INTEGRATOR_KEY,
    SPSEC_KEY_SELECTOR_SEED_KEY,
]

#: Key selectors that can open configuration sessions (Seed key cannot open sessions)
SESSION_KEY_SELECTORS = [
    SPSEC_KEY_SELECTOR_ZERO_KEY,
    SPSEC_KEY_SELECTOR_PROVISIONING_KEY,
    SPSEC_KEY_SELECTOR_INTEGRATOR_KEY,
]

#: Human-readable names for the session selectors, for menus and log lines.
SESSION_KEY_SELECTOR_NAMES = {
    SPSEC_KEY_SELECTOR_ZERO_KEY: "Zero",
    SPSEC_KEY_SELECTOR_PROVISIONING_KEY: "Provisioning",
    SPSEC_KEY_SELECTOR_INTEGRATOR_KEY: "Integrator",
}

# Spec Timouts (SPsec302 / SPsec201)
SESSION_RESPONSE_TIMEOUT_MS = 100
SESSION_TIMEOUT_S = 10

# Register addresses
SPSEC_REG_CAN_FD_BIT_RATE = 0x7B
SPSEC_REG_CODE_UPDATE_CAPABILITIES = 0x90
SPSEC_REG_PUBLIC_AUTH_KEY = 0x91
SPSEC_REG_CODE_UPDATE_FILE = 0x92

# Security Event Codes (SPsec201)
SPSEC_SEC_EVT_NONE = 0x0000
SPSEC_SEC_EVT_AUTH_FAILED = 0x5E01
SPSEC_SEC_EVT_COUNTER_INVALID = 0x5E02
SPSEC_SEC_EVT_REPLAY_DETECTED = 0x5E03
SPSEC_SEC_EVT_TAG_VERIFY_FAILED = 0x5E04
SPSEC_SEC_EVT_UNAUTHORIZED_ACCESS = 0x5E05
